version: "3.8"
services:
  certificates_service:
    image: certificates-service
    container_name: certificates_service_container
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_USERNAME: user
      DB_PASSWORD: admin
      DB_HOST: service_database_container
      DB_PORT: 5432
      DB_NAME: postgres
      JWT_SECRET: iamasecret
  db:
    image: postgres
    container_name: service_database_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@agreena.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: